services:
  postgres:
    image: postgres:17-alpine
    container_name: edu-postgres
    environment:
      POSTGRES_DB: edu_db
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: edu_pass
    ports: [ "15432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: ghcr.io/${GITHUB_REPOSITORY,,}:latest # локально переопредели build контекстом ниже
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/edu
      DB_USER: edu
      DB_PASSWORD: edu
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"


volumes:
  pgdata:
