spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/edu}
    username: ${DB_USER:edu}
    password: ${DB_PASSWORD:edu}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  demo:
    enabled: true   # по умолчанию включено в dev; можно выключить через ENV APP_DEMO_ENABLED=false

# подробное логирование в dev
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springdoc: debug
    org.springdoc.webmvc.api: debug
