spring:
  datasource:
    # URL, username, password — НЕ задаём здесь!
    # Они будут переопределены через @DynamicPropertySource
    # url: jdbc:tc:postgresql:17-alpine:///testdb
    # driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      max-lifetime: 20000      # 20s — меньше дефолта драйвера
      idle-timeout: 10000      # 10s
      validation-timeout: 3000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop  # Лучше create-drop для тестов
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn


